Repository fernandobatels/rsfbclient, pull requests merged in 2020-10, with the labels that each got.

#77 Support for stmt execution without cursor
  rsfbclient-core/src/connection.rs
  rsfbclient-native/src/connection.rs
  rsfbclient-native/src/ibase.rs
  rsfbclient-rust/src/client.rs
  rsfbclient-rust/src/wire.rs
  src/connection/mod.rs
  src/query.rs
  src/statement.rs
  src/tests/row.rs
  src/transaction.rs
Labels: bug, enhancement

#82 add opt-out and opt-in options to ci using labels
  .github/workflows/testing_changes.yml
Labels: prevent-ci

#84 Using borrowed handles in the `FirebirdClient` Trait
  examples/insert.rs
  rsfbclient-core/Cargo.toml
  rsfbclient-core/src/connection.rs
  rsfbclient-derive/Cargo.toml
  rsfbclient-native/src/connection.rs
  rsfbclient-rust/Cargo.toml
  rsfbclient-rust/src/blr.rs
  rsfbclient-rust/src/client.rs
  rsfbclient-rust/src/wire.rs
  src/connection/mod.rs
  src/connection/pool.rs
  src/connection/stmt_cache.rs
  src/statement.rs
  src/tests/transaction.rs
  src/transaction.rs
Labels: enhancement
